/**
 * 8 capacidades de negócio universais — agnósticas de indústria.
 * Verticais reponderam, sobrescrevem labels/placeholders ou adicionam
 * perguntas extra (ver verticals/*.ts) — nunca duplicam esta lista.
 */
import type { Capability } from "./types";

export const CAPABILITIES: Capability[] = [
  {
    id: "aquisicao",
    label: "Aquisição",
    description: "De onde vêm os clientes, quantos por período, quanto esforço custa trazer cada um.",
    questions: [
      {
        id: "aquisicao.origem_principal",
        capabilityId: "aquisicao",
        type: "text",
        label: "Qual é a principal origem de novos clientes?",
        placeholder: "Ex.: indicação, Instagram, Google, porta de rua",
        weight: 0.3,
      },
      {
        id: "aquisicao.volume_mes",
        capabilityId: "aquisicao",
        type: "number",
        label: "Quantos clientes novos chegam por mês, em média?",
        placeholder: "Ex.: 15",
        weight: 0.4,
      },
      {
        id: "aquisicao.canais_ativos",
        capabilityId: "aquisicao",
        type: "enum",
        label: "Quantos canais de aquisição ativos existem hoje?",
        weight: 0.3,
        enumScores: { "nenhum": 0, "um": 30, "dois_ou_tres": 70, "quatro_ou_mais": 100 },
      },
    ],
  },
  {
    id: "conversao",
    label: "Conversão",
    description: "Taxa de fechamento, tempo até decisão do cliente, principal objeção enfrentada.",
    questions: [
      {
        id: "conversao.taxa_fechamento",
        capabilityId: "conversao",
        type: "percent",
        label: "Qual a taxa de conversão de orçamento/contato para venda fechada?",
        placeholder: "Ex.: 25",
        weight: 0.5,
      },
      {
        id: "conversao.objecao_principal",
        capabilityId: "conversao",
        type: "text",
        label: "Qual é a objeção mais comum antes de fechar?",
        placeholder: "Ex.: preço, disponibilidade de agenda, dúvida sobre resultado",
        weight: 0.25,
      },
      {
        id: "conversao.tempo_decisao",
        capabilityId: "conversao",
        type: "duration_minutes",
        label: "Quanto tempo o cliente leva, em média, para decidir depois do primeiro contato?",
        placeholder: "Ex.: 30 (minutos), 1440 (1 dia)",
        weight: 0.25,
      },
    ],
  },
  {
    id: "entrega",
    label: "Entrega",
    description: "Tempo de execução do serviço/produto, capacidade vs. demanda, qualidade percebida.",
    questions: [
      {
        id: "entrega.tempo_execucao",
        capabilityId: "entrega",
        type: "text",
        label: "Quanto tempo leva para entregar o serviço/produto do início ao fim?",
        placeholder: "Ex.: 1 sessão de 1h, 3 dias, entrega imediata",
        weight: 0.35,
      },
      {
        id: "entrega.capacidade_vs_demanda",
        capabilityId: "entrega",
        type: "enum",
        label: "Como está a relação entre capacidade de atendimento e demanda hoje?",
        weight: 0.35,
        enumScores: {
          "sobrecarregado": 20,
          "no_limite": 45,
          "equilibrado": 80,
          "ocioso": 40,
        },
      },
      {
        id: "entrega.qualidade_percebida",
        capabilityId: "entrega",
        type: "text",
        label: "Como o cliente costuma descrever a experiência de entrega/atendimento?",
        placeholder: "Ex.: elogia o cuidado, reclama de demora",
        weight: 0.3,
      },
    ],
  },
  {
    id: "retencao",
    label: "Retenção",
    description: "Recompra, recorrência, tempo médio de relacionamento, motivo de churn conhecido.",
    questions: [
      {
        id: "retencao.taxa_recompra",
        capabilityId: "retencao",
        type: "percent",
        label: "Qual porcentagem dos clientes volta a comprar/contratar de novo?",
        placeholder: "Ex.: 40",
        weight: 0.45,
      },
      {
        id: "retencao.motivo_churn",
        capabilityId: "retencao",
        type: "text",
        label: "Quando um cliente para de voltar, qual costuma ser o motivo?",
        placeholder: "Ex.: preço, mudou de cidade, não sabe",
        weight: 0.25,
      },
      {
        id: "retencao.tempo_relacionamento",
        capabilityId: "retencao",
        type: "number",
        label: "Qual o tempo médio de relacionamento com um cliente, em meses?",
        placeholder: "Ex.: 8",
        weight: 0.3,
      },
    ],
  },
  {
    id: "oferta_precificacao",
    label: "Oferta & Precificação",
    description: "Clareza da oferta, ticket médio, garantia/diferencial declarado.",
    questions: [
      {
        id: "oferta.clareza",
        capabilityId: "oferta_precificacao",
        type: "text",
        label: "Como você descreveria sua oferta principal em uma frase?",
        placeholder: "Ex.: massagem terapêutica para dor crônica em 3 sessões",
        weight: 0.35,
      },
      {
        id: "oferta.ticket_medio",
        capabilityId: "oferta_precificacao",
        type: "number",
        label: "Qual o ticket médio (R$) hoje?",
        placeholder: "Ex.: 250",
        weight: 0.3,
      },
      {
        id: "oferta.diferencial_garantia",
        capabilityId: "oferta_precificacao",
        type: "boolean",
        label: "Existe um diferencial ou garantia clara e comunicada ao cliente?",
        weight: 0.35,
      },
    ],
  },
  {
    id: "operacao_eficiencia",
    label: "Operação & Eficiência",
    description: "Tempo de resposta, ferramentas usadas, gargalo operacional citado.",
    questions: [
      {
        id: "operacao.tempo_resposta",
        capabilityId: "operacao_eficiencia",
        type: "duration_minutes",
        label: "Quanto tempo leva para responder um novo contato?",
        placeholder: "Ex.: 10 (minutos), 60 (1 hora)",
        weight: 0.4,
      },
      {
        id: "operacao.ferramenta_gestao",
        capabilityId: "operacao_eficiencia",
        type: "enum",
        label: "Que ferramenta é usada para gerenciar clientes/agenda?",
        weight: 0.3,
        enumScores: {
          "nenhuma_memoria": 5,
          "planilha": 35,
          "whatsapp_apenas": 25,
          "crm_ou_sistema": 85,
        },
      },
      {
        id: "operacao.gargalo_principal",
        capabilityId: "operacao_eficiencia",
        type: "text",
        label: "Qual é o maior gargalo operacional hoje?",
        placeholder: "Ex.: agenda manual, falta de gente, retrabalho",
        weight: 0.3,
      },
    ],
  },
  {
    id: "capacidade_time",
    label: "Capacidade & Time",
    description: "Pessoas envolvidas, dependência de uma única pessoa (bus factor), divisão de papéis.",
    questions: [
      {
        id: "capacidade.numero_pessoas",
        capabilityId: "capacidade_time",
        type: "number",
        label: "Quantas pessoas trabalham no negócio hoje (incluindo o dono)?",
        placeholder: "Ex.: 1",
        weight: 0.35,
      },
      {
        id: "capacidade.dependencia_unica",
        capabilityId: "capacidade_time",
        type: "boolean",
        label: "O negócio para se essa pessoa principal faltar por uma semana?",
        weight: 0.4,
        invertBoolean: true,
      },
      {
        id: "capacidade.papeis_definidos",
        capabilityId: "capacidade_time",
        type: "boolean",
        label: "Existe divisão clara de papéis/responsabilidades entre quem trabalha ali?",
        weight: 0.25,
      },
    ],
  },
  {
    id: "saude_financeira",
    label: "Saúde Financeira",
    description: "Margem percebida, sazonalidade, previsibilidade de caixa.",
    questions: [
      {
        id: "financeiro.margem_percebida",
        capabilityId: "saude_financeira",
        type: "enum",
        label: "Como você descreveria a margem do negócio hoje?",
        weight: 0.4,
        enumScores: { "no_vermelho": 5, "apertada": 35, "confortavel": 75, "solida": 100 },
      },
      {
        id: "financeiro.sazonalidade",
        capabilityId: "saude_financeira",
        type: "boolean",
        label: "A receita costuma variar muito de mês a mês (sazonalidade forte)?",
        weight: 0.3,
        invertBoolean: true,
      },
      {
        id: "financeiro.previsibilidade_caixa",
        capabilityId: "saude_financeira",
        type: "enum",
        label: "Você sabe, com razoável confiança, quanto vai faturar no mês que vem?",
        weight: 0.3,
        enumScores: { "nao_faco_ideia": 10, "chute_educado": 45, "projecao_confiavel": 90 },
      },
    ],
  },
];
